### PR TITLE
Void Linux plugin, nicer comments outside of functions, checked homepages

### PR DESCRIPTION
**Pull request by zen0bit**
Included changes:
- Added Void Linux plugin
- Nicer comments and before functions not inside
- Fixed some homepages
- Updated template
- Updated all other plugins

### CODE REVIEW

**Comment by zen0bit** [comment]
Please enable Issues in repository

**Review by dabrown645 — CHANGES_REQUESTED** [review]
See comments on template and fix

**Comment by zen0bit** [comment]
Can't find your review comments

**Comment by dabrown645** [comment]
Sorry I am new to being on the receiving end. major comment was about get_files in template. In template get_files should not have any code since quickget provides. It is there to remind people that it can be overridden in the few cases where it is needed.

Also, someone pointed out the there were a bunch of spelling/typing errors I went through all the files with aspell and fixed them so looks like I impacted your request where you moved comments from inside to outside functions . Sorry

Oops. I backed the change out as I didn't so enough testing and broke it I will be redoing to correct this.

**Comment by zen0bit** [comment]
> Sorry I am new to being on the receiving end. major comment was about get_files in template. In template get_files should not have any code since quickget provides. It is there to remind people that it can be overridden in the few cases where it is needed.

Understand but since it is template, should contain examples, and I included mentioned macos(I think) there. Maybe better mention that shouldn't be used by default,or delete that part again..

> Also, someone pointed out the there were a bunch of spelling/typing errors I went through all the files with aspell and fixed them so looks like I impacted your request where you moved comments from inside to outside functions . Sorry
> 
> Oops. I backed the change out as I didn't so enough testing and broke it I will be redoing to correct this.

No problem
I already repaired some spelling errors

Anything else should be changed?

**Comment by dabrown645** [comment]
> Understand but since it is template, should contain examples, and I included mentioned macos(I think) there. Maybe better mention that shouldn't be used by default,or delete that part again..

I guess I don't have an issue with an example but if it is not noted as an example and commented out it will always override the function in quickget. When I reviewed the original quickget it looked like 80% give or take used the same code so I wanted that in quickget but allow for it to be overridden in individual plugin If there is a change to the "standard" get_file I don't want to have to update all the plugins.

Everything else looked good

**Comment by zen0bit** [comment]
Done

**Review by dabrown645 — APPROVED** [review]
Thanks for the help - with practice I will get better on the receiving end of pull requiests.

**Comment by zen0bit** [comment]
🎉 And now merge it, you are a Boss 🎉

**Pull request merged**
